#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CodeRouteAndroid.Resource", IsApplication=true)]

namespace CodeRouteAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bt_choixReponse = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bt_choixReponse2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bt_choixreponse2_a = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bt_choixreponse2_b = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bt_choixreponse_a = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bt_choixreponse_b = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bt_Commencer = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bt_commencer_a = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bt_commencer_b = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bt_Histo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bt_histo_a = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bt_histo_b = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bt_Param = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bt_param_a = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bt_param_b = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bt_qsuivante = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bt_qsuivante_a = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bt_qsuivante_b = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bt_quitter = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bt_quitter_a = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bt_quitter_b = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bt_valid = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bt_valid_a = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bt_valid_b = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Fond = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Fond2 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int FondMain = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int GradientFond = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Icon3 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int QUESTION_Header = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int TELCODEROUTE_Titre = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050016
			public const int MainMenu_Session = 2131034134;
			
			// aapt resource value: 0x7f050023
			public const int Reponse_NbFautes = 2131034147;
			
			// aapt resource value: 0x7f05000b
			public const int blocCheck = 2131034123;
			
			// aapt resource value: 0x7f050014
			public const int btCommencer = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int btHisto = 2131034133;
			
			// aapt resource value: 0x7f050004
			public const int commentaire_lblCommentaire = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int commentaire_lblFautes = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int commentaire_suivant = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int commentaire_txtFautes = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int commentaires_txtCommentaires = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int historique_btValide = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int historique_liste = 2131034119;
			
			// aapt resource value: 0x7f050012
			public const int imgTitre = 2131034130;
			
			// aapt resource value: 0x7f050001
			public const int layoutBt = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int layoutMain = 2131034112;
			
			// aapt resource value: 0x7f050018
			public const int linearLayoutC1 = 2131034136;
			
			// aapt resource value: 0x7f050021
			public const int linearLayoutC2 = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int linearLayoutH1 = 2131034144;
			
			// aapt resource value: 0x7f05000e
			public const int list_check = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int list_numeroQuestion = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int list_valeurReponse = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int listhisto_commentaire = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int listhisto_date = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int listhisto_fautes = 2131034128;
			
			// aapt resource value: 0x7f05001f
			public const int question_btQuitter = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int question_btSuivant = 2131034142;
			
			// aapt resource value: 0x7f050019
			public const int question_toggleA = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int question_toggleB = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int question_toggleC = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int question_toggleD = 2131034140;
			
			// aapt resource value: 0x7f050017
			public const int question_tvQuestion = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int relativeLayout1 = 2131034131;
			
			// aapt resource value: 0x7f050008
			public const int relativeLayout2 = 2131034120;
			
			// aapt resource value: 0x7f05001d
			public const int relativeLayout3 = 2131034141;
			
			// aapt resource value: 0x7f050009
			public const int relativeLayout4 = 2131034121;
			
			// aapt resource value: 0x7f050022
			public const int reponse_listview = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int response_btValide = 2131034148;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Commentaire = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Historique = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int list_detail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list_histo_detail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainMenu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Question = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Reponse = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int EnterButton = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int EnterProtein = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int Goals = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int GoalsButton = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int TestData = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
